window:
  padding:
    x: 5
    y: 5 
  class: 
    instance: Alacritty
    general: Alacritty

scrolling: 
  history: 10000
  multiplier: 3

font:
  normal: 
    family: MesloLGS NF
    style: Regular
  bold:
    family: MesloLGS NF
    style: Bold
  italic:
    family: MesloLGS NF
    style: Italic
  bold_italic:
    family: MesloLGS NF
    style: Bold Italic
  size: 15 
draw_bold_text_with_bright_colors: true

import:
 - ~/.config/alacritty/themes/themes/tokyo-night.yaml
